server:
  port: 31003
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: course-manage
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/,file:D:/file/
  datasource:
    url: jdbc:mysql://www.wuhourong.top:3306/xc_course?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: wu
    password: 19980122
  data:
    mongodb:
      database: xc_cms
      host: www.wuhourong.top
      port: 27017
    elasticsearch:
      cluster-name: cluster
      cluster-nodes: www.wuhourong.top:9300
  mail:
    host: smtp.qq.com
    username: 876565575@qq.com
    password: ilgwjrmihgkrbeic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 30MB
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: www.wuhourong.top
    username: wu
    password: Wu19980122

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    use-actual-param-name: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

mybatis-plus:
#   \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/*/*/mapper/*Mapper.xml
#   \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/**.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.xc: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} %msg%n'

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer‐ip‐address: true #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

course-publish:
  siteId: 5a751fab6abb5044e0d19ea1
  templateId: 5dfcefd0d7440e3808da73b7
  previewUrl: http://www.xuecheng.com/cms/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrl: http://localhost:31003/course/allInfo/
