server:
  port: ${port:40100}
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: cluster
      cluster-nodes: www.wuhourong.top:9300
xuecheng:
  elasticsearch:
    hostlist: ${eshostlist:www.wuhourong.top:9200}